# Generated by Django 3.2.18 on 2023-09-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlists',
            options={'verbose_name_plural': 'Item lists'},
        ),
    ]
