# Generated by Django 3.2.18 on 2023-09-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_alter_itemlists_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='value',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
