# Generated by Django 3.2.18 on 2023-09-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPortions',
        ),
    ]
