# Generated by Django 3.2.18 on 2023-09-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portions', '0003_menuportions'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuportions',
            name='item_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
