# Generated by Django 3.2.18 on 2023-09-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portions', '0006_alter_menuportions_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuportions',
            name='item_description',
        ),
    ]
