# Generated by Django 3.2.18 on 2023-09-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portions', '0007_remove_menuportions_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuportions',
            name='ingredient_cost',
            field=models.DecimalField(decimal_places=2, default=1, help_text='ingredients cost in gm/ml/units', max_digits=25),
            preserve_default=False,
        ),
    ]
