# Generated by Django 3.2.18 on 2023-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portions', '0008_menuportions_ingredient_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuportions',
            name='ingredient_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ingredients cost in gm/ml/units', max_digits=25, null=True),
        ),
    ]
