# Generated by Django 3.2.18 on 2023-09-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portions', '0009_alter_menuportions_ingredient_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuportions',
            old_name='ingredient',
            new_name='amount_changed',
        ),
        migrations.RenameField(
            model_name='menuportions',
            old_name='ingredient_cost',
            new_name='single_price_changed',
        ),
    ]
