# Generated by Django 3.2.18 on 2023-09-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portions', '0010_auto_20230908_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuportions',
            old_name='amount_changed',
            new_name='item_amount',
        ),
        migrations.RenameField(
            model_name='menuportions',
            old_name='single_price_changed',
            new_name='item_cost',
        ),
    ]
