# Generated by Django 3.2.18 on 2023-09-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portions', '0011_auto_20230908_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuportions',
            name='item_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='menuportions',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=25),
            preserve_default=False,
        ),
    ]
