# Generated by Django 3.2.18 on 2023-09-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in kg/ltr', max_digits=25)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per kg/ltr', max_digits=25)),
                ('date_of_purchased', models.DateField()),
                ('date_of_expired', models.DateField()),
                ('batch_number', models.PositiveIntegerField(blank=True, null=True)),
                ('barcode', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('provider_website', models.CharField(blank=True, max_length=120, null=True)),
                ('provider_address', models.TextField(blank=True, max_length=250, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.measurement')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.itemlists')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
