# Generated by Django 3.2.18 on 2023-09-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='price',
            new_name='single_price',
        ),
        migrations.AddField(
            model_name='items',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price per kg/ltr', max_digits=25),
            preserve_default=False,
        ),
    ]
