# Generated by Django 3.2.18 on 2023-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20230904_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ingredient',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Amount used for menu portion', max_digits=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='single_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per measurement', max_digits=25),
        ),
        migrations.AlterField(
            model_name='items',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
