# Generated by Django 3.2.18 on 2023-09-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20230904_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ingredient',
            field=models.CharField(max_length=100),
        ),
    ]
