# Generated by Django 3.2.18 on 2023-09-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_items_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ingredient',
            field=models.DecimalField(decimal_places=2, help_text='Amount used for menu portion', max_digits=25),
        ),
    ]
