# Generated by Django 3.2.18 on 2023-09-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_items_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ingredient',
            field=models.CharField(max_length=100),
        ),
    ]
