# Generated by Django 3.2.18 on 2023-09-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20230907_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='ingredient',
            new_name='changed_amount',
        ),
    ]
