# Generated by Django 3.2.18 on 2023-09-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_rename_ingredient_items_changed_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='changed_amount',
            new_name='amount_changed',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='single_price_in_gm_ml',
            new_name='single_price_changed',
        ),
    ]
