# Generated by Django 3.2.6 on 2023-09-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20230908_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='items',
            name='single_price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='items',
            name='single_price_changed',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
