# Generated by Django 3.2.18 on 2023-09-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20230906_2040'),
        ('margins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmargins',
            name='menu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menus', unique=True),
        ),
    ]
