# Generated by Django 3.2.18 on 2023-09-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('margins', '0002_alter_allmargins_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmargins',
            name='total_margin',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
