# Generated by Django 3.2.18 on 2023-09-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCost',
        ),
    ]
