# Generated by Django 3.2.18 on 2023-09-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('menu_name', models.CharField(max_length=100, unique=True)),
                ('menu_description', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
