# Generated by Django 3.2.18 on 2023-09-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menus',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=25),
            preserve_default=False,
        ),
    ]
