# Generated by Django 3.2.18 on 2023-09-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20230906_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='total_utility_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=25),
            preserve_default=False,
        ),
    ]
