# Generated by Django 3.2.18 on 2023-09-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menus_total_utility_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menus',
            old_name='total_utility_cost',
            new_name='utility_cost',
        ),
    ]
