# Generated by Django 3.2.18 on 2023-09-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=25)),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menus')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
